
["CASINO CONFIG"]
	#Allows Betting Inventory to be set to INFINITE
	config_creative_token = true
	#Allows Reward Inventory to be set to INFINITE
	config_creative_reward = true
	#Only Operators on a Server or Singleplayer with Cheats enabled can set INFINITE
	config_creative_oponly = false
	#How long until a player receives a timeout
	#Range: 1 ~ 10000
	config_timeout = 300

